from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet

from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

import os



def register_font():


    """
    Register Chinese font if available
    """


    font_paths = [

        "C:/Windows/Fonts/msyh.ttc",

        "/System/Library/Fonts/STHeiti Light.ttc",

        "/usr/share/fonts/truetype/wqy/wqy-zenhei.ttc"

    ]


    for path in font_paths:


        if os.path.exists(path):


            pdfmetrics.registerFont(
                TTFont(
                    "CustomFont",
                    path
                )
            )


            return "CustomFont"



    return "Helvetica"





def create_pdf(report, path):


    font = register_font()



    doc = SimpleDocTemplate(
        path
    )



    styles = getSampleStyleSheet()



    for style in styles.byName.values():

        style.fontName = font



    content = []



    # =========================
    # Title
    # =========================


    content.append(

        Paragraph(

            "AI Credit Risk Assessment Report",

            styles["Title"]

        )

    )


    content.append(
        Spacer(1,20)
    )



    # =========================
    # Summary Table
    # =========================


    table_data = [


        [
            "Risk Score",
            str(
                report.get(
                    "Risk Score",
                    ""
                )
            )
        ],


        [
            "Risk Level",
            report.get(
                "Risk Level",
                ""
            )
        ],


        [
            "Decision",
            report.get(
                "Decision",
                ""
            )
        ]

    ]



    table = Table(
        table_data
    )



    table.setStyle(

        TableStyle(

            [

                (
                    "GRID",
                    (0,0),
                    (-1,-1),
                    0.5,
                    None
                )

            ]

        )

    )



    content.append(
        table
    )


    content.append(
        Spacer(1,20)
    )



    # =========================
    # Summary
    # =========================


    content.append(

        Paragraph(

            "Risk Summary",

            styles["Heading2"]

        )

    )


    content.append(

        Paragraph(

            report.get(
                "Summary",
                ""
            ),

            styles["BodyText"]

        )

    )



    content.append(
        Spacer(1,15)
    )



    # =========================
    # Risk Factors
    # =========================


    content.append(

        Paragraph(

            "Risk Factors",

            styles["Heading2"]

        )

    )



    factors = report.get(

        "Risk Factors",

        []

    )



    for factor in factors:


        content.append(

            Paragraph(

                "• " + str(factor),

                styles["BodyText"]

            )

        )



    content.append(
        Spacer(1,15)
    )



    # =========================
    # Recommendation
    # =========================


    content.append(

        Paragraph(

            "Recommendation",

            styles["Heading2"]

        )

    )



    content.append(

        Paragraph(

            report.get(

                "Recommendation",

                ""

            ),

            styles["BodyText"]

        )

    )



    content.append(
        Spacer(1,20)
    )



    content.append(

        Paragraph(

            "Generated by AI Credit Risk System",

            styles["BodyText"]

        )

    )



    doc.build(
        content
    )